#+OPTIONS: toc:nil num:nil
* Card Captor Sakura
:PROPERTIES:
:HTML_LINK: ./anime/cardcaptor.html
:END:
      This show is near and dear to my heart if only for having a dvd of it that I watched on repeat as a child.
      It's a pretty standard magical girl anime that has it's fair share of self aware jabs at the genre it belongs to.
      IDK I just think it's cute.
* Lucky Star
:PROPERTIES:
:HTML_LINK: ./anime/luckystar.html
:END:
      I watched this around middle school and couldn't understand why. It was among the somewhat "closeted" I guess I
      would say media properties I enjoyed at the time.
      There's something about the absolutely mundane types of things the show focuses on and presents so enjoyably that
      in a lot of ways taught me how to more thoroughly enjoy myself.
      Lucky star taught me a lot even with such a simple message, it was a view on life I desparetly needed someone else
      to validate was okay to believe.
      Damn, didn't realize I had such strong feelings about this show till I started writing about it.
* Steven Universe
:PROPERTIES:
:HTML_LINK: ./anime/steven.html
:END:
      Steven has one of the most esteemed and special places in my heart as far as shows go.
      I watched it at a deeply pivotal and transformative time in my life where I felt quite alone and without anyone
      who understood me.
      This show sincerely helped me feel less alone in some of the hardest times of my life, told me that a life based
      in truth and lvoe was something worth fighting for.
